package com.urlshotener.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006399)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcbe5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d32)
val md_theme_light_secondary = Color(0xFF51606f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd4e4f6)
val md_theme_light_onSecondaryContainer = Color(0xFF0d1d2a)
val md_theme_light_tertiary = Color(0xFF67587a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFeedbff)
val md_theme_light_onTertiaryContainer = Color(0xFF221534)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfcfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdee3eb)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72777e)
val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3032)

val md_theme_dark_primary = Color(0xFF90ccff)
val md_theme_dark_onPrimary = Color(0xFF003352)
val md_theme_dark_primaryContainer = Color(0xFF004b75)
val md_theme_dark_onPrimaryContainer = Color(0xFFcbe5ff)
val md_theme_dark_secondary = Color(0xFFb8c8da)
val md_theme_dark_onSecondary = Color(0xFF233240)
val md_theme_dark_secondaryContainer = Color(0xFF394857)
val md_theme_dark_onSecondaryContainer = Color(0xFFd4e4f6)
val md_theme_dark_tertiary = Color(0xFFd2bfe7)
val md_theme_dark_onTertiary = Color(0xFF372a49)
val md_theme_dark_tertiaryContainer = Color(0xFF4e4161)
val md_theme_dark_onTertiaryContainer = Color(0xFFeedbff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe2e2e5)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe2e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val md_theme_dark_outline = Color(0xFF8c9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e5)

val seed = Color(0xFF7c97b1)
val error = Color(0xFFba1b1b)

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)

val DarkBackground = Color(0xFF4E4E4E)
val LightBackground = Color(0xFFE0E0E0)

val PrimaryDark = Color(0xFF90ccff)
val onPrimaryDark = Color(0xFF003352)
val ErrorDark = Color(0xFFffb4a9)

val PrimaryLight = Color(0xFF006399)
val onPrimaryLight = Color(0xFFffffff)
val ErrorLight = Color(0xFFba1b1b)

val Primary = Color(0xffb6d5d8)
val Secondary = Color(0xffd3c5bc)